/**
 * Mangalist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BookDto {
    isbn: string;
    title: string | null;
    subtitle: string | null;
    publishedDate: string | null;
    description: string | null;
    pageCount: number | null;
    printedPageCount: number | null;
    language: string | null;
    createdAt: string;
    updatedAt: string;
    publisherId: string | null;
    bookCoverId: string | null;
    groupId: string | null;
}
