/**
 * backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Enums
 */
export type BookStatus = 'NONE' | 'OWNED' | 'WHISHLISTED';

export const BookStatus = {
    None: 'NONE' as BookStatus,
    Owned: 'OWNED' as BookStatus,
    Whishlisted: 'WHISHLISTED' as BookStatus,
};
