/**
 * backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Model Book
 */
export interface Book {
    publisherId: string | null;
    updatedAt: string;
    createdAt: string;
    language: string | null;
    printedPageCount: number | null;
    pageCount: number | null;
    description: string | null;
    publishedDate: string | null;
    subtitle: string | null;
    title: string | null;
    isbn: string;
}
