/**
 * backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookStatus } from './bookStatus';

/**
 * Model OwnershipStatus
 */
export interface OwnershipStatus {
    bookIsbn: string;
    userId: number;
    updatedAt: string;
    createdAt: string;
    status: BookStatus;
}
