/**
 * Booklify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LegalDto } from './legalDto';
import { RecaptchaDto } from './recaptchaDto';
import { ReportsDto } from './reportsDto';

export interface SystemInfoDto {
    signUpEnabled: boolean;
    recaptcha: RecaptchaDto;
    legal: LegalDto;
    reports: ReportsDto;
    version: string;
}
