apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "booklify.fullname" . }}-backend
  labels:
    {{- include "booklify.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "booklify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        {{ randAlphaNum 5 | quote }}: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "booklify.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "booklify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: backend-config
          configMap:
            name: backend-config-{{ .Values.backend.config | toJson | sha256sum }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - name: http-backend
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /system/health
              port: http-backend
          readinessProbe:
            httpGet:
              path: /system/health
              port: http-backend
          volumeMounts:
            - name: backend-config
              mountPath: /app/config/production.json5
              subPath: production.json5
              readOnly: true
          env:
            - name: DATABASE_URL
              value: {{ .Values.backend.config.db.url }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
