apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "booklify.fullname" . }}-frontend
  labels:
    {{- include "booklify.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "booklify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}

        {{- toYaml . | nindent 8 }}
      {{- end }}
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "booklify.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "booklify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          ports:
            - name: http-frontend
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http-frontend
          readinessProbe:
            httpGet:
              path: /
              port: http-frontend
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
