version: '2.8'
services:
    dev_db:
        image: postgres:15-alpine
        environment:
            - POSTGRES_USER=uwu
            - POSTGRES_PASSWORD=owo
            - POSTGRES_DB=mangalist
        ports:
            - 5432:5432
    s3:
        image: adobe/s3mock:latest
        ports:
            - 9090:9090
        environment:
            - root=/s3mockroot
            - retainFilesOnExit=true
        volumes:
            - ./data/s3:/s3mockroot/mangalist:rw
    cdn:
        image: ghcr.io/nginxinc/nginx-s3-gateway/nginx-oss-s3-gateway:latest
        ports:
            - 8080:80
        env_file: config/.test.env
