name: companion_app
description: A new Flutter project.
publish_to: 'none'
version: 1.2.3+8

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.0.0
  mobile_scanner: ^4.0.0
  checkbox_formfield: ^0.2.0
  email_validator: ^3.0.0
  checkdigit: ^0.3.1
  http: ^1.1.0
  shared_preferences: ^2.2.1
  cached_network_image: ^3.2.3
  url_launcher: ^6.2.2
  flutter_launcher_icons: ^0.13.1
  dio: ^5.4.1

  booklify_api:
    path: ./booklify_api

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21