name: companion_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.0.0
  mobile_scanner: ^3.4.1
  checkbox_formfield: ^0.2.0
  email_validator: ^2.1.17
  checkdigit: ^0.3.1
  http: ^1.1.0
  shared_preferences: ^2.2.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true