export * from './auth.service';
import { AuthService } from './auth.service';
export * from './books.service';
import { BooksService } from './books.service';
export * from './general.service';
import { GeneralService } from './general.service';
export * from './session.service';
import { SessionService } from './session.service';
export * from './snapshot.service';
import { SnapshotService } from './snapshot.service';
export const APIS = [AuthService, BooksService, GeneralService, SessionService, SnapshotService];
